"""esquema inicial de lecciones

Revision ID: f427c4e663f7
Revises:
Create Date: 2026-10-04 17:45:53.079623
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "f427c4e663f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("lugar", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("icono", sa.String(length=40), nullable=False),
        sa.Column("tablas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archivo", sa.LargeBinary(), nullable=False),
        sa.Column("archivo_sha256", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_datasets")),
    )
    op.create_table(
        "modulos",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_modulos")),
        sa.UniqueConstraint("orden", name=op.f("uq_modulos_orden")),
    )
    op.create_table(
        "lecciones",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("modulo_slug", sa.String(length=40), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=160), nullable=False),
        sa.Column("resumen", sa.Text(), nullable=False),
        sa.Column("duracion_min", sa.Integer(), nullable=False),
        sa.Column("dataset_slug", sa.String(length=40), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "aprenderas",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("secciones", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_slug"], ["datasets.slug"], name=op.f("fk_lecciones_dataset_slug_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["modulo_slug"], ["modulos.slug"], name=op.f("fk_lecciones_modulo_slug_modulos")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_lecciones")),
        sa.UniqueConstraint("orden", name=op.f("uq_lecciones_orden")),
    )
    op.create_table(
        "ejercicios",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("leccion_slug", sa.String(length=60), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("enunciado_md", sa.Text(), nullable=False),
        sa.Column("solucion_sql", sa.Text(), nullable=False),
        sa.Column("ordenado", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("resultado_esperado", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["leccion_slug"], ["lecciones.slug"], name=op.f("fk_ejercicios_leccion_slug_lecciones")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ejercicios")),
        sa.UniqueConstraint("leccion_slug", "orden", name=op.f("uq_ejercicios_leccion_slug")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ejercicios")
    op.drop_table("lecciones")
    op.drop_table("modulos")
    op.drop_table("datasets")
    # ### end Alembic commands ###
